name: Build and push Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: attid/walletconnect_bridge

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:latest

      #- name: Notify Telegram
      #  run: |
      #    curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
      #      -H "Content-Type: application/json" \
      #      -d '{"chat_id": "-1003339919065", "text": "Docker image pushed to registry /info_walletconnect_bridge"}'
          
